# Generated by Django 4.2 on 2023-04-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(default='http://example.com', max_length=100),
        ),
    ]
